inherit:
    - counterfactual.yaml

model:
    family: "gpt2_sde"
    n_embd: 256
    n_positions: 60

training:
    batch_size: 8
    data: "sde"
    train_steps: 10000
    diversity: 6400000
    save_every_steps: 7000
    curriculum:
        vars:           # curriculum learning on DAG complexity
            start: 2    # binary DAG
            end: 2
            inc: 1
            interval: 8000

wandb:
    name: "sde"